# Property of RÃ­an Errity Licensed under GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007. See <LICENSE.md>
# Thank you for using Paradaux's AutoBroadcast v2.0.0

# How long, in seconds, between announcements. The default is 15 to show all the examples
interval: 15

# This enables functionality which may break your AutoBroadcast Experience.
# Any user with the "autobroadcast.bypass" permission will not receive broadcasts (including operators and users with "*")
# For this reason, this is disabled by default.
enable-bypass-permission: false

# Make multiple-line announcements by using \n to begin a new line.
# These announcements use the MiniMessgae format. You cannot use &-codes like &4
# See the MiniMessage documentation: https://docs.adventure.kyori.net/minimessage.html

# It allows for custom gradients, click events and loads more!
# Here's some example usage:

announcements:
  - "<gray>Thanks for installing <red>AutoBroadcast</red>!"
  - "<click:run_command:/say hello>Click me</click> to say hello"
  - "<gradient:#5e4fa2:#f79459:red>Click <click:copy_to_clipboard:Haha you suck>this</click> to copy to your clipboard"
  - "<bold><click:open_url:https://docs.adventure.kyori.net/minimessage.html>Click here to learn more about MiniMessage"
  - "<hover:show_text:'<red>check out this sick <rainbow>rainbow'>Hover over me"
  - "<red>Here<gray> is an \nexample of a \nmultiple-line message."
  - "<gray>Once you have <red>updated<gray> your <gray>configuration<gray> make sure to <red>reload<grey> the plugin!\n<gray>/<red>autobroadcast reload <gray>:: <red>reloads<gray> the configuration files"

# Whether or not announcements will be broadcast in a random order, otherwise they are repeated in the defined-order.
randomize-announcements: false

# Disabling bStats

# If you don't want bStats to collect data from your server, you can disable it in the bStats config file. This file can be found in the /plugins/bStats/ folder.
# bStats has nearly no effect on your server's performance and the sent data is completely anonymous. The collected data is important information for plugin authors
# to improve their plugins and keep motivated. To value their work and effort, please keep bStats enabled.

bstats_enabled: true

# bStats does not collect any personal data. Most of the collected data is information about the plugin's server like player count, online mode,
# Minecraft version, Java version, and more. All data gets sent and stored completely anonymously. Server IPs are only stored for rate-limiting
# and not linked to the data. All data that is collected is publicly visible. If you are interested in what data is collected for your Minecraft
# server, take a look at the pages for the plugins on your server. Please note that plugin authors can also send data that is customized for their plugin.
# https://bstats.org/plugin/bukkit/HiberniaAutoBroadcast/9185

# Force-disabling bStats

# If you don't trust me, and my settings, bStats has its own system to disable plugins' bStats.

# Do not edit, this may break the plugin or your configuration file.
config-version: 2.0